version: '3.8'
services:
  mongo:
    image: mongo:5.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/library
    depends_on:
      - mongo

volumes:
  mongo-data:
