version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env-example
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: {}